[package]
name = "quarkstrom"
version = "0.1.0"
edition = "2024"

[dependencies]
# Graphics
wgpu = "27.0.1"
winit = "0.30.12"
winit_input_helper = "0.17.0"

# Gui
egui = "0.33.0"
egui-wgpu = "0.33.0"
egui-winit = "0.33.0"

# Math
ultraviolet = "0.10.0"
fastrand = "2.3.0"

# Other
bytemuck = { version = "1.24.0", features = [ "derive" ] }
pollster = "0.4.0"
once_cell = "1.21.3"